Add Laravel 7 support
laravel-notification-channels/pushover pull request #40
Opened 2020-03-05 22:34 UTC by kapersoft

Fixes https://github.com/laravel-notification-channels/pushover/issues/39

2020-03-05 23:53 UTC, atymic requested changes

2020-03-05 23:53 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^7.0",
```suggestion
        "illuminate/notifications": "~5.5 || ^6.0 || ^7.0",
```

Single pipe is deprecated + can clean up reqs here :)

2020-03-05 23:53 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^7.0",
(and below)

2020-03-05 23:53 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^7.0",
(also need to allow testbench 4/5 for laravel 6/7

2020-03-06 21:30 UTC, kapersoft commented
@atymic PR is updated with the requested changes

2020-03-06 23:02 UTC, atymic approved these changes

2020-03-07 20:38 UTC, casperboone commented
Thx!

2020-03-07 20:38 UTC, merged